AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - '*.gemspec'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'lib/weka_jars.rb'

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 105

Metrics/ClassLength:
  Max: 250

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "**/*_spec.rb"

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Style/HashEachMethods:
  Exclude:
    - lib/weka/core/instances.rb
    - spec/classifiers/evaluation_spec.rb

Naming/PredicateName:
  Exclude:
    - lib/weka/core/instances.rb

Metrics/CyclomaticComplexity:
  Max: 8
