AllCops:
  TargetRubyVersion: 3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - '*.gemspec'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'lib/weka_jars.rb'

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "**/*_spec.rb"

Lint/BooleanSymbol:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 105

Style/HashEachMethods:
  Exclude:
    - lib/weka/core/instances.rb
    - spec/classifiers/evaluation_spec.rb

Naming/PredicatePrefix:
  Exclude:
    - lib/weka/core/instances.rb
