name: JRuby CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: jruby:9

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run Tests
      run: bundle exec rake
